### PR TITLE
feat(lint): add eslint

### PR DESCRIPTION
**Pull request by serge1peshcoff**
copied the eslint config from core + disabled a few rules (no-console, func-names), auto-linted everything.

the only error I have now is 

```
/Users/sergeypeshkov/oms-docker/hubot-slack-docker/scripts/myaegeedeployer.js
  16:29  error  Unable to resolve path to module 'node-ssh'  import/no-unresolved
```

and this is something I want to fix in a later PR when refactoring bootstrapping (moving all deps into package.json)

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
possible next step: copy-pasting the CircleCI config to have it as a PR check, then making it required

**Review by linuxbandit — APPROVED** [review]

**Comment by linuxbandit** [comment]
i don't get the package.json tho, won't it interfere with the package.json of hubot?

**Comment by serge1peshcoff** [comment]
It isn't copied to the container, so no. Also this is something I will refactor in the next PR (my idea is to get rid of the bootstrap script and replacing it with simple package.json containing hubot and all the deps, and npm install).

**Comment by linuxbandit** [comment]
I don't like it: In that way it will be less dynamic that simply adding a name to the array(s) of names (in the docker compose and extra-packages.json). You'd have to add it to package.json instead of 2 different places, sure, but you'll have to add the version

**Comment by linuxbandit** [comment]
but as you said, it's for another PR (which I discourage), so this is gtg

**Comment by serge1peshcoff** [comment]
yeah, forgot to merge it

**Pull request merged**
